# Cloudflare Pages Configuration for Next.js
name = "max-verstappen-dashboard"
compatibility_date = "2024-04-07"
pages_build_output_dir = "out"

# D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "maxdb"
database_id = "6d53b703-c3cb-49a9-a570-3cb705834e16"

# Environment variables
[env.production]
NODE_ENV = "production"

[env.preview]
NODE_ENV = "development"
