# Cloudflare Pages Configuration

name = "max-verstappen-dashboard"
compatibility_date = "2024-08-09"

[build]
command = "npm run build"
publish = "out"

[[build.environment_variables]]
NODE_VERSION = "18"

[env.production]
NEXT_PUBLIC_ENV = "production"

[env.preview]
NEXT_PUBLIC_ENV = "preview"
