# Cloudflare Pages Configuration for Next.js
name = "max-verstappen-dashboard"
compatibility_date = "2024-04-07"
pages_build_output_dir = "out"

# Environment variables
[env.production]
NODE_ENV = "production"

[env.preview]
NODE_ENV = "development"
